# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: training.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'training.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etraining.proto\"\x15\n\x03\x41\x63k\x12\x0e\n\x06status\x18\x01 \x01(\t\"C\n\tImageData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x14\n\x0cground_truth\x18\x02 \x01(\t\x12\x12\n\nprediction\x18\x03 \x01(\t\")\n\x0b\x42\x61tchUpdate\x12\x1a\n\x06images\x18\x01 \x03(\x0b\x32\n.ImageData\"-\n\nLossUpdate\x12\x0c\n\x04loss\x18\x01 \x01(\x02\x12\x11\n\titeration\x18\x02 \x01(\x05\x32\\\n\x0eTrainingStream\x12%\n\x0fSendBatchUpdate\x12\x0c.BatchUpdate\x1a\x04.Ack\x12#\n\x0eSendLossUpdate\x12\x0b.LossUpdate\x1a\x04.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'training_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACK']._serialized_start=18
  _globals['_ACK']._serialized_end=39
  _globals['_IMAGEDATA']._serialized_start=41
  _globals['_IMAGEDATA']._serialized_end=108
  _globals['_BATCHUPDATE']._serialized_start=110
  _globals['_BATCHUPDATE']._serialized_end=151
  _globals['_LOSSUPDATE']._serialized_start=153
  _globals['_LOSSUPDATE']._serialized_end=198
  _globals['_TRAININGSTREAM']._serialized_start=200
  _globals['_TRAININGSTREAM']._serialized_end=292
# @@protoc_insertion_point(module_scope)
