# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import training_pb2 as training__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in training_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrainingStreamStub(object):
    """Name of the server / service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendBatchUpdate = channel.unary_unary(
                '/TrainingStream/SendBatchUpdate',
                request_serializer=training__pb2.BatchUpdate.SerializeToString,
                response_deserializer=training__pb2.Ack.FromString,
                _registered_method=True)
        self.SendLossUpdate = channel.unary_unary(
                '/TrainingStream/SendLossUpdate',
                request_serializer=training__pb2.LossUpdate.SerializeToString,
                response_deserializer=training__pb2.Ack.FromString,
                _registered_method=True)


class TrainingStreamServicer(object):
    """Name of the server / service
    """

    def SendBatchUpdate(self, request, context):
        """Will create a SendBatchUpdate and SendLossUpdate call
        Takes in a BatchUpdate and LossUpdate message
        Returns an Ack to the client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendLossUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainingStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendBatchUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SendBatchUpdate,
                    request_deserializer=training__pb2.BatchUpdate.FromString,
                    response_serializer=training__pb2.Ack.SerializeToString,
            ),
            'SendLossUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SendLossUpdate,
                    request_deserializer=training__pb2.LossUpdate.FromString,
                    response_serializer=training__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TrainingStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('TrainingStream', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrainingStream(object):
    """Name of the server / service
    """

    @staticmethod
    def SendBatchUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TrainingStream/SendBatchUpdate',
            training__pb2.BatchUpdate.SerializeToString,
            training__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendLossUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TrainingStream/SendLossUpdate',
            training__pb2.LossUpdate.SerializeToString,
            training__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
